server:
    # 端口号
    port: 8884
    servlet:
        context-path: /simulation
spring:
    application:
        name: athena-simulation
simulation:
    # 服务器IP地址
    serverIp: "172.16.42.206"
    # 服务器端口号
    port: 8899
    # 充电站端口号
    chargerPort: 8898
    # 起始的机器人ID 默认+1
    startId: 1003
    # 初始机器人电量
    power: 90
    # 初始机器人角度
    angle: 0
    # 机器人类型，支持P，M与F，F表示叉车
    type: "P"
    # 批量添加机器人 num表示数量，x表示初始的X坐标，y表示初始的Y坐标，cellCode优先，使用cellCode会向服务器请求地图数据（非标二维码地图模式支持）
    #  space为0表示在X轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    #  space为1表示在Y轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    robots:
                - x: 7.15
                  y: 4.55
                - x: 8.45
                  y: 4.55
                - x: 9.75
                  y: 4.55
                - x: 11.05
                  y: 4.55
                - x: 12.35
                  y: 4.55
                - x: 13.65
                  y: 4.55
                - x: 14.95
                  y: 4.55
                - x: 16.25
                  y: 4.55
                - x: 17.55
                  y: 4.55
                - x: 18.85
                  y: 4.55
            