server:
    # 端口号
    port: 8884
    servlet:
        context-path: /simulation
spring:
    application:
        name: athena-simulation
simulation:
    # 服务器IP地址
    serverIp: "172.16.42.63"
    # 服务器端口号
    port: 8899
    # 充电站端口号
    chargerPort: 8898
    # 起始的机器人ID 默认+1
    startId: 1003
    # 初始机器人电量
    power: 90
    # 初始机器人角度
    angle: 0
    # 机器人类型，支持P，M与F，F表示叉车
    type: "P"
    # 批量添加机器人 num表示数量，x表示初始的X坐标，y表示初始的Y坐标，cellCode优先，使用cellCode会向服务器请求地图数据（非标二维码地图模式支持）
    #  space为0表示在X轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    #  space为1表示在Y轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    robots:
            - x: 13.975
              y: 29.4
            - x: 15.35
              y: 29.4
            - x: 16.35
              y: 29.4
            - x: 17.825
              y: 29.4
            - x: 18.825
              y: 29.4
            - x: 20.3
              y: 29.4
            - x: 21.3
              y: 29.4
            - x: 23.375
              y: 29.4
            - x: 24.95
              y: 29.4
            - x: 25.95
              y: 29.4
            - x: 27.375
              y: 29.4
            - x: 28.375
              y: 29.4
            - x: 29.825
              y: 29.4
            - x: 13.975
              y: 30.4
            - x: 15.35
              y: 30.4
            - x: 16.35
              y: 30.4
            - x: 17.825
              y: 30.4
            - x: 18.825
              y: 30.4
            - x: 20.3
              y: 30.4
            - x: 21.3
              y: 30.4
            - x: 23.375
              y: 30.4
            - x: 24.95
              y: 30.4
            - x: 25.95
              y: 30.4
            - x: 27.375
              y: 30.4
            - x: 28.375
              y: 30.4
            - x: 29.825
              y: 30.4
            - x: 11.975
              y: 31.4
            - x: 12.975
              y: 31.4
            - x: 33.275
              y: 31.4
            - x: 12.975
              y: 32.8



