server:
    # 端口号
    port: 8884
    servlet:
        context-path: /simulation
spring:
    application:
        name: athena-simulation
simulation:
    # 服务器IP地址
    serverIp: "172.16.41.193"
    # 服务器端口号
    port: 8899
    # 充电站端口号
    chargerPort: 8898
    # 起始的机器人ID 默认+1
    startId: 1003
    # 初始机器人电量
    power: 90
    # 初始机器人角度
    angle: 0
    # 机器人类型，支持P，M与F，F表示叉车
    type: "P"
    # 批量添加机器人 num表示数量，x表示初始的X坐标，y表示初始的Y坐标，cellCode优先，使用cellCode会向服务器请求地图数据（非标二维码地图模式支持）
    #  space为0表示在X轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    #  space为1表示在Y轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    robots:
            - x: 9.775
              y: 11.475
            - x: 10.925
              y: 11.475
            - x: 13.225
              y: 11.475
            - x: 14.375
              y: 11.475
            - x: 15.525
              y: 11.475
            - x: 17.825
              y: 11.475
            - x: 18.975
              y: 11.475
            - x: 20.125
              y: 11.475
            - x: 21.275
              y: 11.475
            - x: 23.575
              y: 11.475