server:
    # 端口号
    port: 8884
    servlet:
        context-path: /simulation
spring:
    application:
        name: athena-simulation
simulation:
    # 服务器IP地址
    serverIp: "172.16.43.3"
    # 服务器端口号
    port: 8899
    # 充电站端口号
    chargerPort: 8898
    # 起始的机器人ID 默认+1
    startId: 1003
    # 初始机器人电量
    power: 90
    # 初始机器人角度
    angle: 0
    # 机器人类型，支持P，M与F，F表示叉车
    type: "P"
    # 批量添加机器人 num表示数量，x表示初始的X坐标，y表示初始的Y坐标，cellCode优先，使用cellCode会向服务器请求地图数据（非标二维码地图模式支持）
    #  space为0表示在X轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    #  space为1表示在Y轴方向放置机器人，spaceNumber表示机器人之间的间隔距离
    robots:
                - x: 16.75
                  y: 53.42
                  power: 53
                - x: 16.75
                  y: 54.59
                - x: 19.49
                  y: 55.76
                - x: 20.86
                  y: 55.76
                - x: 24.22
                  y: 55.76
                - x: 25.59
                  y: 55.76
                - x: 28.33
                  y: 55.76
                - x: 29.7
                  y: 55.76
                - x: 32.44
                  y: 55.76
                - x: 33.81
                  y: 55.76
                - x: 38.63
                  y: 55.76
                - x: 40.0
                  y: 55.76
                - x: 42.74
                  y: 55.76
                - x: 44.11
                  y: 55.76
                - x: 45.48
                  y: 55.76
                - x: 50.96
                  y: 55.76
                - x: 52.33
                  y: 55.76
                - x: 55.07
                  y: 55.76
                - x: 56.44
                  y: 55.76
                - x: 59.18
                  y: 55.76
                - x: 16.75
                  y: 56.93
                - x: 19.49
                  y: 56.93
                - x: 20.86
                  y: 56.93
                - x: 24.22
                  y: 56.93
                - x: 25.59
                  y: 56.93
                - x: 28.33
                  y: 56.93
                - x: 29.7
                  y: 56.93
                - x: 32.44
                  y: 56.93
                - x: 33.81
                  y: 56.93
                - x: 38.63
                  y: 56.93
                - x: 40.0
                  y: 56.93
                - x: 50.96
                  y: 56.93
                - x: 52.33
                  y: 56.93
                - x: 55.07
                  y: 56.93
                - x: 56.44
                  y: 56.93
                - x: 59.18
                  y: 56.93
                - x: 16.75
                  y: 58.1
                - x: 19.49
                  y: 58.1
                - x: 20.86
                  y: 58.1
                - x: 25.59
                  y: 58.1
                - x: 28.33
                  y: 58.1
                - x: 29.7
                  y: 58.1
                - x: 32.44
                  y: 58.1
                - x: 38.63
                  y: 58.1
                - x: 50.96
                  y: 58.1
                - x: 52.33
                  y: 58.1
                - x: 56.44
                  y: 58.1
                - x: 59.18
                  y: 58.1
                - x: 16.75
                  y: 59.27
                - x: 19.49
                  y: 59.27
                - x: 20.86
                  y: 59.27
                - x: 25.59
                  y: 59.27
                - x: 28.33
                  y: 59.27
                - x: 29.7
                  y: 59.27
                - x: 32.44
                  y: 59.27
                - x: 50.96
                  y: 59.27
                - x: 52.33
                  y: 59.27
                - x: 56.44
                  y: 59.27
                - x: 59.18
                  y: 59.27
                - x: 16.75
                  y: 60.44
                - x: 19.49
                  y: 60.44
                - x: 20.86
                  y: 60.44
                - x: 24.22
                  y: 60.44
                - x: 25.59
                  y: 60.44
                - x: 28.33
                  y: 60.44
                - x: 29.7
                  y: 60.44
                - x: 32.44
                  y: 60.44
                - x: 33.81
                  y: 60.44
                - x: 50.96
                  y: 60.44
                - x: 52.33
                  y: 60.44
                - x: 55.07
                  y: 60.44
                - x: 56.44
                  y: 60.44
                - x: 59.18
                  y: 60.44
                - x: 16.75
                  y: 61.61
                - x: 19.49
                  y: 61.61
                - x: 20.86
                  y: 61.61
                - x: 24.22
                  y: 61.61
                - x: 25.59
                  y: 61.61
                - x: 28.33
                  y: 61.61
                - x: 29.7
                  y: 61.61
                - x: 32.44
                  y: 61.61
                - x: 33.81
                  y: 61.61
                - x: 38.63
                  y: 61.61
                - x: 40.0
                  y: 61.61
                - x: 50.96
                  y: 61.61
                - x: 52.33
                  y: 61.61
                - x: 55.07
                  y: 61.61
                - x: 56.44
                  y: 61.61
                - x: 59.18
                  y: 61.61
                - x: 19.49
                  y: 62.78
                - x: 20.86
                  y: 62.78
                - x: 24.22
                  y: 62.78
                - x: 25.59
                  y: 62.78
                - x: 28.33
                  y: 62.78
                - x: 29.7
                  y: 62.78
                - x: 32.44
                  y: 62.78
                - x: 33.81
                  y: 62.78
                - x: 38.63
                  y: 62.78
                - x: 40.0
                  y: 62.78
                - x: 50.96
                  y: 62.78







#            - x: 15.6
#              y: 22.1
#              type: "F"
#            - x: 11.38
#              y: 19.14
#              type: "F"
#              angle: 270
#            - x: 15.6
#              y: 18.07
#              type: "F"
#              angle: 90
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180
#
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180
#            - x: 13.248
#              y: 24.223
#              type: "F"
#              angle: 180



